server.port: 8763
 
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
 
logging.level.com.netflix.eureka: OFF
logging.level.com.netflix.discovery: OFF
 

eureka.instance.preferIpAddress: true
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka

spring.application.name: eureka-server