server:
  port: 8008

spring:
  application:
    name: service-auth


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/
      
feign:
  hystrix:
    enabled: true

mybatis.mapper-locations: classpath:/com/gradex_cloud/dao/*Dao.xml
mybatis.type-aliases-package: com.gradex_cloud.pojo
mybatis.configuration.cache-enabled: true

spring.datasource.url: jdbc:mysql://localhost:3306/gradexcloud?characterEncoding=UTF-8&useSSL=false
spring.datasource.username: root
spring.datasource.password: jmcDB!!
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver

