server:
  port: 8002

spring:
  application:
    name: service-consumer
 # security:
 #   oauth2:
 #     resourceserver:
 #       jwt:
 #         issuer-uri: http://localhost:8008/auth/user/getPrinciple

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/
feign:
  hystrix:
    enabled: true

security.oauth2.resource.userInfoUri: http://localhost:8008/auth/user/getPrinciple
hystrix.command.default.execution.isolation.strategy: SEMAPHORE