server:
  port: 8001
  
spring:
  application:
    name: service-provider
 # security:
 #   oauth2:
 #     resourceserver:
 #       jwt:
 #         issuer-uri: http://localhost:8008/auth/user/getPrinciple
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
    
security.oauth2.resource.userInfoUri: http://localhost:8008/auth/user/getPrinciple
