server:
  port: 5001

spring:
  application:
    name: service-gateway-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8763/eureka/
      
zuul:
  sensitive-headers: Cookie,Set-Cookie